name:       "meadowstalk"
version:    "2.0.0"
synopsis:   "Blake Rain's Blog"
maintainer: "Blake Rain <blake.rain@meadowstalk.com>"
license:    "BSD3"
github:     "HalfWayMan/meadowstalk"
category:   "Web"

ghc-options: -Wall

flags:
  library-only:
    manual: true
    default: false

dependencies:
  - aeson
  - base
  - directory
  - containers
  - filepath
  - monad-logger
  - template-haskell
  - transformers
  - process

  - blaze-html
  - bytestring
  - cheapskate
  - data-default
  - friendly-time
  - pwstore-fast
  - shakespeare
  - text
  - time

  - esqueleto
  - persistent
  - persistent-postgresql
  - persistent-template
  
  - yesod-core
  - yesod-form
  - yesod-newsfeed
  - yesod-persistent
  - yesod-sitemap
  - yesod-static

  - wai
  - wai-extra

library:
  when:
    condition: flag(library-only)
    then:
      ghc-options: -O0
      cpp-options: -DYESOD_DEVEL
    else:
      ghc-options: -O2
    
  source-dirs: src
  exposed-modules:
    - Meadowstalk.Application
  other-modules:
    - Meadowstalk.Controllers.Article
    - Meadowstalk.Controllers.Tag
    - Meadowstalk.Foundation
    - Meadowstalk.Handlers.Public
    - Meadowstalk.Model
    - Meadowstalk.Model.Types
    - Meadowstalk.Static
    - Meadowstalk.Template
    - Meadowstalk.Views

executables:
  meadowstalk:
    when:
      condition: flag(library-only)
      buildable: false
    main: Main.hs
    source-dirs: src
    dependencies:
      - meadowstalk
      - warp
  article-importer:
    when:
      condition: flag(library-only)
      buildable: false
    main: ArticleImporter.hs
    source-dirs: src
    dependencies:
      - meadowstalk
      - yaml
  migrator:
    when:
      condition: flag(library-only)
      buildable: false
    main: Migrator.hs
    source-dirs: src
    dependencies:
      - meadowstalk
